# Caso practico: Neurona de McCulloch y Pitts

## Implementacion de MPNeuron

In [3]:
import numpy as np

In [18]:
import numpy as np

class MPNeuron:
    def __init__(self):
        self.threshold = None

    def model(self, x):
        # input: [x1, x2, x3, ... xn]
        z = sum(x)
        return (z >= self.threshold)
    
    def predict(self, X):
        # input: [[1,0,1,0], [1,0,1,1]]
        Y = []
        for x in X:
            result = self.model(x)
            Y.append(result)
        return np.array(Y)

## Intanciamos la clase 

In [19]:
mp_neurona = MPNeuron()

In [22]:
mp_neurona.threshold=3

In [23]:
#1 pasi y 0 para no
mp_neurona.predict([[1,1,0,0],[1,1,0,1],[1,0,0,0]])

array([False,  True, False])

### Implementando compuerta logica AND

In [28]:
mp_neurona.threshold=2
mp_neurona.predict([[0,0,1,1],[0,0,0,1]])

array([ True, False])

### Implementando Compuerta Logica OR

In [29]:
mp_neurona.threshold=1
mp_neurona.predict([[0,0,1,1],[0,0,0,1]])

array([ True,  True])